sudo: required
language: python
services:
  - docker
python:
  - "2.7"
before_install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - "sudo service mysql-5.6 stop || sudo service mysql stop"
  - make test
install:
  - sleep 10
script: pytest && flake8
after_success:
  - codecov
