version: '2'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - /tmp/git-webhook-data/mysql:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
  redis:
    image: redis:3
    volumes:
      - /tmp/git-webhook-data/redis:/data
    ports:
      - "6379:6379"
